# run main.py
name: Auto Sign
on:
  schedule:
    # 服务器在美国芝加哥：时间2026-03-11 01:00对应的北京时间是 2026-03-11 14:00
    # 定时表达式 cron: '0 1 * * *'，北京时间 2026-03-12 01:00（UTC+08），但执行效果是美国芝加哥：2026-03-11 11:00:00（UTC-05）
    - cron: '0 14 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install cryptography
      - name: Run main.py
        env:
          GitHub_Actions: true
          # 对于多个账号一定会有人机验证问题，且因为是密码，有一定的安全风险
          # PHONE: ${{ secrets.PHONE }}
          # PASSWORD: ${{ secrets.PASSWORD }}
          TOKEN: ${{ secrets.TOKEN }}
          SC3_SENDKEY: ${{ secrets.SC3_SENDKEY }}
          SC3_UID: ${{ secrets.SC3_UID }}
          EXIT_WHEN_FAIL: ${{ vars.EXIT_WHEN_FAIL }}
        run: |
          python src/main.py
